# Generated by Django 5.2.1 on 2025-05-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.BooleanField(default=True),
        ),
    ]
